export const initialState = {
  productName: "",
  brand: "",
  model: "",
  description: "",
  mrp: "",
  price: "",
  quantity: "",
  minOrderQty: "1",
  maxOrderQty: "",
  categoryId: "",
  subCategory: "",
  gst: "12",
  condition: "New",
  warranty: "",
  weight: "",
  length: "",
  width: "",
  height: "",
  fulfilledBy: "seller",
  images: [],
  specifications: [
    { key: "", value: "" },
    { key: "", value: "" },
    { key: "", value: "" },
  ],
  tags: [],
};
