export const CONTRACTS = [
  {
    id: 1,
    name: "Annual Copper Supply",
    companyId: 101,
    party: "Kumar Recyclers",
    value: "₹48L",
    start: "Jan 2025",
    end: "Dec 2025",
    status: "active",
    material: "Copper Scrap",
    quantity: "120 MT",
    paymentTerms: "Net 30",
    location: "Pune, Maharashtra",
  },

  {
    id: 2,
    name: "Steel Procurement Q4",
    companyId: 102,
    party: "Sharma Metals",
    value: "₹22L",
    start: "Apr 2025",
    end: "Oct 2025",
    status: "expiring",
    material: "Steel Scrap",
    quantity: "80 MT",
    paymentTerms: "Advance 50%",
    location: "Mumbai, Maharashtra",
  },

  {
    id: 3,
    name: "E-Waste Disposal SLA",
    companyId: 101,
    party: "Gupta Eco Recycling",
    value: "₹9L",
    start: "Jun 2025",
    end: "Mar 2026",
    status: "active",
    material: "Electronic Waste",
    quantity: "25 MT",
    paymentTerms: "Net 15",
    location: "Bengaluru, Karnataka",
  },

  {
    id: 4,
    name: "Plastic Recycling MOU",
    companyId: 103,
    party: "Sharma Plastics",
    value: "₹7L",
    start: "Feb 2025",
    end: "Aug 2025",
    status: "expired",
    material: "Plastic Scrap",
    quantity: "40 MT",
    paymentTerms: "Net 45",
    location: "Hyderabad, Telangana",
  },

  {
    id: 5,
    name: "Aluminium Bulk Purchase",
    companyId: 101,
    party: "National Alloy Traders",
    value: "₹31L",
    start: "May 2025",
    end: "Jan 2026",
    status: "active",
    material: "Aluminium Scrap",
    quantity: "65 MT",
    paymentTerms: "Advance 30%",
    location: "Chennai, Tamil Nadu",
  },

  {
    id: 6,
    name: "Paper Waste Recovery Contract",
    companyId: 104,
    party: "EcoFiber Pvt Ltd",
    value: "₹5L",
    start: "Mar 2025",
    end: "Sep 2025",
    status: "expiring",
    material: "Paper Waste",
    quantity: "90 MT",
    paymentTerms: "Net 20",
    location: "Delhi NCR",
  },

  {
    id: 7,
    name: "Glass Scrap Annual Agreement",
    companyId: 101,
    party: "Crystal Reclaimers",
    value: "₹12L",
    start: "Jul 2025",
    end: "Jul 2026",
    status: "active",
    material: "Glass Scrap",
    quantity: "50 MT",
    paymentTerms: "Monthly Settlement",
    location: "Ahmedabad, Gujarat",
  },

  {
    id: 8,
    name: "Industrial Textile Waste Deal",
    companyId: 105,
    party: "GreenTex Industries",
    value: "₹14L",
    start: "Jan 2025",
    end: "Nov 2025",
    status: "active",
    material: "Textile Waste",
    quantity: "70 MT",
    paymentTerms: "Net 60",
    location: "Surat, Gujarat",
  },

  {
    id: 9,
    name: "Mixed Scrap Collection Contract",
    companyId: 101,
    party: "Urban Scrap Solutions",
    value: "₹18L",
    start: "Apr 2025",
    end: "Apr 2026",
    status: "active",
    material: "Mixed Scrap",
    quantity: "110 MT",
    paymentTerms: "Biweekly",
    location: "Nagpur, Maharashtra",
  },

  {
    id: 10,
    name: "Battery Recycling Partnership",
    companyId: 106,
    party: "VoltCycle Energy",
    value: "₹26L",
    start: "May 2025",
    end: "Feb 2026",
    status: "expiring",
    material: "Battery Waste",
    quantity: "35 MT",
    paymentTerms: "Net 10",
    location: "Noida, Uttar Pradesh",
  },
];
